name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Run Tests and Measure Coverage
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10] 
        cpu-cores: [2, 4, 8] 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install pytest and pytest-cov for coverage

      - name: Run tests with pytest and collect coverage
        run: |
          pytest --cov=note_api --maxfail=1 --disable-warnings -v  # Run tests with coverage
          
  # Submit coverage to Codecov or CodeClimate
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Make sure to set up a token in your GitHub secrets

  # Security Scan using Snyk
  snyk-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v2
        
      - name: Run Snyk Security Scan
        run: snyk test --all-projects  # Ensure your Snyk project is correctly set up

  # Build Docker Container and Push to GitHub Container Registry
  docker-build:
    runs-on: ubuntu-latest
    needs: [test, snyk-scan]  # Ensure tests and security scan pass before building Docker image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub's built-in token

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-project:latest  # Change the repository name accordingly

