name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Measure Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov codecov snyk

      - name: Run Tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=note_api tests/

      - name: Upload Coverage to Codecov
        if: success()
        run: |
          bash <(curl -s https://codecov.io/bash)

  security-scan:
    name: Security Scan with snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install snyk
        run: |
          curl -sL https://static.snyk.io/snyk/install.sh | bash
          export PATH=$PATH:$(pwd)/.snyk
          pip install -r requirements.txt

      - name: Run snyk Security Scan
        run: snyk test --all-projects

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}

