name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Ensure the workflow has the necessary permissions
permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: note-api-hs-heilbronn-devsecops-dateam  # GCP project ID
  REGION: europe-west3  # GCP region
  REPOSITORY: note-api  # Artifact Registry repository name
  WORKLOAD_IDENTITY_PROVIDER: projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos  # Workload Identity Provider
  SERVICE_ACCOUNT: hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com  # Service Account for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    # Step 3: Install project dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Install additional development dependencies
    - name: Install development dependencies
      run: pip install -r requirements-dev.txt

    # Step 5: Run tests and collect code coverage
    - name: Run pytest with coverage
      run: pytest --cov=note_api -n auto

    # Step 6: Upload coverage results to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # Step 7: Perform security scan
    - name: Snyk Security Scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Step 8: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    # Step 9: Build Docker image
    - name: Build Docker image
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t ghcr.io/${{ github.repository }}:${SHORT_SHA} .

    # Step 10: Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker push ghcr.io/${{ github.repository }}:${SHORT_SHA}

    # Step 11: Authenticate with Google Cloud using Workload Identity Federation
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    # Step 12: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Step 13: Configure Docker for Google Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    # Step 14: Tag and Push Docker image to Google Artifact Registry
    - name: Push Docker image to Artifact Registry
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ github.ref_name }}:${SHORT_SHA}"
        docker tag ghcr.io/${{ github.repository }}:${SHORT_SHA} $IMAGE_URI
        docker push $IMAGE_URI

    # Step 15: Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.REPOSITORY }}
        image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ github.ref_name }}:${SHORT_SHA}"
        region: ${{ env.REGION }}
        env_vars: BACKEND=memory
